name: simpleBank-transaction-test

on:
  push:
    branches: [transaction]
  # pull_request:
  #   branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # - name: Checkout the module in transfer branch
      #   uses: actions/checkout@v2

      - name: Test
        run: make test
