name: simpleBank-transaction-test

on:
  push:
    branches: [transaction]
  # pull_request:
  #   branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgress:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run migrations
        run: make migrateup

      # - name: Checkout the module in transfer branch
      #   uses: actions/checkout@v2

      - name: Test
        run: make test
